### ISSUE TITLE
error: failed to compile `atosl v0.1.10`, intermediate artifacts can be found at `/tmp/cargo-installFZcnqp`

### ISSUE THREAD

**Issue by srs888001** [everettjf/atosl-rs#2]
我在我的linux机器上运行报错：
系统: CentOS Linux release 7.5.1804 (Core) 
rust版本:  rustc 1.58.0 (02072b482 2022-01-11)
gcc版本：gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC) 
报错详情:[err.log](https://github.com/everettjf/atosl-rs/files/7881985/err.log)

我mac机子上是可以编译成功的。 我猜测是不是还缺少什么环境。
能帮我看下问题吗？

**Comment by everettjf** [comment]
看起来是symbolic-demangle 这个库导致，但原因我还不知道。明天我试试找个centos

**Comment by srs888001** [comment]
老哥， 有进展吗？

**Comment by everettjf** [comment]
老哥加我微信聊: everettjf ……我的m1似乎没有办法安装linux虚拟机
________________________________
发件人: JerrySi ***@***.***>
发送时间: Thursday, January 20, 2022 8:45:06 PM
收件人: everettjf/atosl-rs ***@***.***>
抄送: everettjf ***@***.***>; Comment ***@***.***>
主题: Re: [everettjf/atosl-rs] error: failed to compile `atosl v0.1.10`, intermediate artifacts can be found at `/tmp/cargo-installFZcnqp` (Issue #2)


老哥， 有进展吗？

―

**Comment by everettjf** [comment]
close了哈。ubuntu可以这样：

```
# install guide for ubuntu
sudo apt update
sudo apt install git
sudo apt install curl
sudo apt install build-essential
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
cargo install atosl
```

centos没有测试（不知道为啥虚拟机安装不上，不研究啦）。肯定是编译问题啦哈
