### ISSUE TITLE
Wrong code for iOS crash DWARF files

### ISSUE THREAD

**Issue by TommyLemon** [everettjf/atosl-rs#3]
Thank you for making this tool open, I now can symbolicate DWARF files, while the result is not what I want.
it used .debug_aranges(ASLR slide), maybe there is something wrong about calculating offset?

https://github.com/everettjf/atosl-rs/blob/main/src/atosl.rs#L241-L260
![image](https://user-images.githubusercontent.com/5738175/158303276-0255244e-e6c6-4c90-b921-4f3a7bea9fe2.png)

Please fix this problem or tell me how to. Thank you very much~

References:
https://eli.thegreenplace.net/2011/12/26/the-contents-of-dwarf-sections
https://bellis1000.medium.com/aslr-the-ios-kernel-how-virtual-address-spaces-are-randomised-d76d14dc7ebb
https://en.wikipedia.org/wiki/Address_space_layout_randomization#iOS_(iPhone,_iPod_touch,_iPad)

**Comment by everettjf** [comment]
发下dSYM文件、地址和aslr ？

**Comment by TommyLemon** [comment]
抱歉公司不允许把资料发到外部网络哈，最近再次测试发现大部分文件名、类名、方法名是对的了，
可能因为之前装了太多 dwarfdump, facebook/atosl, llvm-dwarfdump, glimi 之类的包导致有冲突，
也可能你最近更新了 cargo 仓库的 atosl-rs，解决了 文件名、类名、方法名 不正确的问题。

不过目前还有不少代码行号是错的，会显示为 0 、空字符串或其它数字
例如  XXX (in XX) + 123 (XXX.swift:0)，XXX (in XX) + 123 (XXX.swift:) 或 XXX (in XX) + 123 (XXX.swift:828) 
实际上应该为  XXX (in XX) + 123 (XXX.swift:848) 这样的，
话说 .debug_lines 中 [ 0, 0 ] , [848, 12], [828, 15] 确实也都对应同一个方法，看起来行号和方法是多对一的关系
```shell
Thread 0 Crashed:
0   XX                      0x000011814a 0x1280000 + 123456
1   XX                      0x000012b33e 0x1280000 + 134863
```
两行地址和偏移量虽然不一样，但实际上用 MacOS atos 解析出来的文件名、类名、方法名、行号等全都是一样的。
第 0 行地址行号应该是 848，用这个项目解析为 0，错误；
第 1 行地址行号应该是 848，用这个项目解析为 848，正确。

我看到这个项目本身代码也不多，逻辑也比较简单，
DWARF 文件解析依赖底层的 glimi 等其它项目，是否因为它们的 bug 导致的呢？
https://github.com/everettjf/atosl-rs/blob/main/Cargo.toml#L14

如果依赖的版本不是最新的，可以升级下再发个 cargo 包给我试试，非常感谢~

**Comment by TommyLemon** [comment]
https://github.com/everettjf/atosl-rs/blob/main/src/atosl.rs#L335
https://github.com/everettjf/atosl-rs/blob/main/src/atosl.rs#L354

崩溃日志中涉及任何代码都不可能是代码文件第 0 行，所以我加了个判断
```rs
if (found_line > 0) {
  break;
}
```

但我因为没做过 Rust 开发，目前是用 IntelIJ IDEA + Rust 插件查看和编辑源码，还不会打包和部署（需要在 Ubuntu 上可用）

**Comment by everettjf** [comment]
收到，我仔细看看哈

**Comment by everettjf** [comment]
发了个版本0.1.13，加上了这两个判断。具体原因我抽空再学习下dsym格式了哈

**Comment by TommyLemon** [comment]
关于 iOS 系统 14.x 和 15.x 测试了 8 个版本以及相关的 500+ .ips 文件，都几乎完全正确（匹配 Mac 工具 atos 符号化结果）。
但是涉及 App 及第三方库的的代码，除了 Objective-C 基本完全正确，Swift 代码仍然有约 10%-30% 的地方出现行号甚至代码（文件名、方法名）错误。抱歉相关文件都是公司内网的，不能外发。
期待作者解决，非常感谢~

**Comment by everettjf** [comment]
给力，感谢支持。swift我这确实没检查过，抽空研究下
________________________________
发件人: TommyLemon ***@***.***>
发送时间: Wednesday, April 27, 2022 12:20:47 AM
收件人: everettjf/atosl-rs ***@***.***>
抄送: everettjf ***@***.***>; State change ***@***.***>
主题: Re: [everettjf/atosl-rs] Wrong code for iOS crash DWARF files (Issue #3)


关于 iOS 系统 14.x 和 15.x 测试了 8 个版本以及相关的 500+ .ips 文件，都几乎完全正确（匹配 Mac 工具 atos 符号化结果）。
但是涉及 App 及第三方库的的代码，除了 Objective-C 基本完全正确，Swift 代码仍然有约 10%-30% 的地方出现行号甚至代码（文件名、方法名）错误。抱歉相关文件都是公司内网的，不能外发。
期待作者解决，非常感谢~

―
